### ISSUE TITLE
dose ffigen support namespace?

### ISSUE THREAD

**Issue by hy2991** [dart-lang/ffigen#108]
i have a header using a namespace, when i run `pub run ffigen`, it occurred an error

**Comment by mannprerak2** [comment]
Hi @hy2991 
`namespace` is a C++ feature, whereas ffigen (and dart:ffi) only works with C.

**Comment by hy2991** [comment]
> Hi @hy2991
> `namespace` is a C++ feature, whereas ffigen (and dart:ffi) only works with C.

lol

**Comment by mannprerak2** [comment]
@hy2991 
I hope this issue is no longer relevant, I am closing this now, but feel free to reopen this if you want.
