### ISSUE TITLE
Working with the unified `dart` tool

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#109]
Starting from dart 2.10,  a new unified `dart` command (consistent with `flutter`) has been added. According to the [announcement](https://medium.com/dartlang/announcing-dart-2-10-350823952bd5#837b:~:text=Next%20year%20we%20expect%20to%20ship,tool%20when%20running%20Dart%20commands%20now), by next year other smaller tools will be removed. 

Here are the changes we need to do -
- [x] Use `dart format` instead of `dartfmt` for [formatting generated files](https://github.com/dart-lang/ffigen/blob/master/lib/src/code_generator/library.dart#L99).
- [x] Update readme(s) and comments to use `dart pub get` instead of `pub get`.

We should wait for these tools to be removed (as long as we can) before we update `ffigen`'s SDK constraint to be >=2.10,
OR, we can also try calling `dart format` and if that fails, try running `dartfmt`.

cc @dcharkes

**Comment by dcharkes** [comment]
We might want to allow users to use `ffigen` (with any features that we might add still) with version 2.9 as long as possible.

We can keep this issue open for the time being.
Or, we could do `dart --version` if we want a bit cleaner solution than a fallback.
Whatever you prefer.

@bkonyi @mit - is there a timeline for deprecating `dartfmt` & `pub`?

**Comment by mit-mit** [comment]
We expect to mark those commands deprecated in the next stable release, and then discontinue then 1-2 stable releases later.

**Comment by mannprerak2** [comment]
Closed via #148.
