### ISSUE TITLE
Missing nested typedef dependencies from a typedef's return type.

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#115]
Any typedefs which are only used in the return type of another typedef aren't currently being generated.

One example is when running this on `dart_api.h`. The generated bindings is missing this -
```dart
typedef _typedefC_1 = ffi.Void Function(
  ffi.Pointer<_Dart_NativeArguments>,
);
``` 

Thanks to [@Donaled](https://github.com/Dolaned) for finding this.

**Comment by Dolaned** [comment]
no worries mate 👍
