### ISSUE TITLE
Support Dart_Handle from dart_api.h

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#120]
In https://github.com/dart-lang/sdk/commit/6544c69e23256f7d60498e6f5f66a395a008587f we added support for passing any Dart `Object` to native as a `Dart_Handle` from the [dart_api.h](https://github.com/dart-lang/sdk/blob/master/runtime/include/dart_api.h).

It would be nice if we could use `package:ffigen` to automatically generate bindings for `Dart_Handle`.

* c type to recognise: `Dart_Handle`
* type marker to generate for C type signatures in Dart: `Handle`
* Dart type to generate: `Object`

For more info see the CL and the tests/examples added in the CL.

**Comment by mannprerak2** [comment]
How to handle something like `Dart_Handle* a`, can we simply generate `Pointer<Handle>` for this?

**Comment by dcharkes** [comment]
Uh I guess, but users can't unwrap a `Pointer<Handle>` to `Object` without using a trampoline.

`Dart_Handle`s in C/C++ are scoped. That means such a type could only occur on a callback, and the pointer would be invalid when the callback returns.

Do you have a concrete example?

**Comment by mannprerak2** [comment]
> Do you have a concrete example?

Not really, I just wanted to know if there is a reason to treat this differently. I wasn't sure if someone would even do something like that, so I just wanted to confirm.
