### ISSUE TITLE
Apply members of struct to the dart-bool option 

### ISSUE THREAD

**Issue by larryaasen** [dart-lang/ffigen#131]
I have a struct that uses a `bool` member type. It generates `ffi.NativeFunction<bool>` when using option `dart-bool: false` with ffigen version 1.2.0. Can the members of `struct` be applied to the `dart-bool` option so the `bool` types are generated as `int` instead?

Example of a C struct:
```
struct video_info {
	bool gpu_conversion;
};
```

Current output:
```
class video_info extends ffi.Struct {
  ffi.NativeFunction<bool> gpu_conversion;
}
```

Would like this to be:
```
class video_info extends ffi.Struct {
  @ffi.Uint8()
  int gpu_conversion;
}
```

**Comment by mannprerak2** [comment]
> with ffigen version 0.1.3

Can you try with the latest stable version? (1.2.0)

**Comment by larryaasen** [comment]
@mannprerak2 Sorry, I was using 1.2.0, but incorrectly wrote 0.1.3, which was the version of `ffi`. The description has been corrected.

**Comment by mannprerak2** [comment]
Hi @larryaasen, I am not able to reproduce this. The `dart-bool` option only applies to generated functions (not inside structs).

Can you send me ffigen's output, it seems to me there are missing headers which is causing this, which would have been logged by ffigen.

**Comment by larryaasen** [comment]
@mannprerak2 I am not able to send the output because it is over 50k lines. The struct generated produced this Dart error: 
```
Fields in struct classes can't have the type 'ffi.NativeFunction<bool>'. They can only be declared as 'int', 'double' or 'Pointer'.
Try using 'int', 'double' or 'Pointer'.
```
I'm using Dart 2.12.0 (build 2.12.0-141.0.dev)

**Comment by mannprerak2** [comment]
The type `ffi.NativeFunction<bool>` shouldn't exist in C. This is probably happening because of some missing headers.
LibClang tries to automatically try and fix these errors which can cause these issues.

You need to check if ffigen is printing any `SEVERE: ...` logs. If it is, you need to fix them, otherwise, the bindings generated wouldn't be correct.

If you can copy the output logs of ffigen into a github gist and then send a link to that, I can help you identify the error.

**Comment by larryaasen** [comment]
Yes, I found one SEVERE:  `fatal error: 'stdbool.h' file not found [Lexical or Preprocessor Issue]`
This is the line of code that has the include directive:
```
#include <stdbool.h>
```
These two lines above it worked fine:
```
#include <stddef.h>
#include <stdint.h>
```

**Comment by mannprerak2** [comment]
You need to find the location of this header and supply it in the compiler opts with an `-I` flag.

```yaml
compiler-opts: "-Ipath/to/header/folder"
```

**Comment by larryaasen** [comment]
The file stdbool.h is in the same folder as stddef.h and stdint.h. Since those were found, shouldn't stdbool.h be found?

**Comment by larryaasen** [comment]
This worked:
```
compiler-opts: '-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/'
```
However, I would not expect this to be needed because the other files were found in the same folder.

**Comment by mannprerak2** [comment]
It's probably not using that directory then. 
The stdbool.h file on MacOS is not available in the system headers by default. I had to include it like this, https://github.com/dart-lang/ffigen/blob/bdd6c4a3fa5d5d68410abd1b18b11c2aef6be9dd/test/native_test/config.yaml#L21)

You can try and compile a small C file with stdbool.h using `clang` and it will fail.

**Comment by larryaasen** [comment]
OK, thanks that works as well. I guess this issue is now resolved.
