### ISSUE TITLE
Make a preview release for Dart 2.12. beta

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#149]
We should make a preview release for the Dart 2.12 beta, in anticipation of the Dart 2.12 stable release.

The version number of this package does not need a suffix anymore.

See 'preview' release on package:ffi for example. https://pub.dev/packages/ffi/versions

**Comment by mannprerak2** [comment]
We can do a preview version after merging #147 and #148 (where we upgrade all dependencies).  
`package:quiver` however, still uses a suffix in its latest null safe version. Should we wait for it to make a preview release first?

**Comment by dcharkes** [comment]
https://pub.dev/packages/ffigen/versions/2.0.0

**Comment by dcharkes** [comment]
https://pub.dev/packages/quiver/versions/3.0.0, we can release a 2.0.1.
