### ISSUE TITLE
Merge dart-dev into master

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#153]
With the Dart 2.12 beta soon moving to Dart 2.12 stable, we should merge our dart-dev branch (which is on beta) into the master branch.

https://github.com/dart-lang/ffigen/compare/dart-dev?expand=1

We can keep dart-dev around if we'd like to continue working on supporting `dart:ffi` features as they get available on dev. (Maybe we should delete the dart-master branch? If I recall correctly, running tests on master requires building the whole Dart SDK on the Ci just to run the tests.)

**Comment by mannprerak2** [comment]
> Maybe we should delete the dart-master branch? 

Yes we should.

> We can keep dart-dev around if we'd like to continue working on supporting dart:ffi

Sure.

**Comment by dcharkes** [comment]
@mannprerak2 can you take a look at the merge conflicts between master and dart-dev?

**Comment by mannprerak2** [comment]
Yeah sure, I'll create a PR by tomorrow.

**Comment by dcharkes** [comment]
Done: #161, #163, #164, #165, #166, #167, and #168.
