### ISSUE TITLE
Only generate non-included structs as Opaque if only referenced by pointer

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#176]
https://github.com/dart-lang/ffigen/blob/89084d968ce0d587b19290366762ab7af7ffbe61/README.md#L474-L477

If `struct`s are only referenced by `Pointer<struct>` we should generate them as `Opaque` if they are not included.

For example [here](https://github.com/google/webcrypto.dart/blob/b5c79268214ac1af2b1835dbc3a0584cdb436d79/lib/src/third_party/boringssl/generated_bindings.dart#L3646-L3683).

If someone wants the full struct, they can include it.

**Comment by mannprerak2** [comment]
Iit's not always practical to include structs manually in config (since there could be a lot of them).

So I think we should probably keep this behind a flag (Something like `opaque-excluded-structs`?, default: false).
With this, ffigen will generate complete structs by default, but if the option is enabled, structs that were not included would be Opaque if referenced only with Pointer<struct>.

**Comment by dcharkes** [comment]
> It's not always practical to include structs manually in config (since there could be a lot of them).

So far, in using BoringSSL it's been only a dozen.

> I think we should probably keep this behind a flag

Agreed.

I'm not entirely sure about what the default should be. When generating `Opaque` you cannot allocate them nor access their fields, but if the API only uses pointers to the struct anyway it's likely that you'll always interact through the pointer. (This is at least true for BoringSSL and SQLite.) So, I think the default should be generate them as `Opaque`. However, there might be C APIs out there which do only expose pointers to structs in their API but still expect you to either access the structs fields or to allocate them yourself. Do you know of any?

> (Something like `opaque-excluded-structs`?, default: false)

```yaml
structs:
  include:
    - MyStruct
  dependencies: full | opaque
```

The structs that are pulled into the generated code because they are _dependencies_ are either generated fully or opaque. wdyt?

**Comment by mannprerak2** [comment]
> `dependencies: full | opaque`

This seems cool too. But I think the default should be `full`, since it doesn't really affect the usage of the library if they were completely generated instead of being Opaque (but not the other way around). I'd like the bindings to be complete if the user hasn't specified explicitly.

**Comment by dcharkes** [comment]
> I'd like the bindings to be complete if the user hasn't specified explicitly.

That's fair.

I was approaching it the other way around, I'd like to generate as small a set of bindings for my use case as possible.

**Comment by mannprerak2** [comment]
On second thought, I think we should have a top level key called `struct-dependencies` with value `full or opaque`.
Nesting it under `structs` makes it seems like this only targets dependencies for structs and not dependencies of functions.
