### ISSUE TITLE
/// // comments

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#186]
```dart
  /// // BN_free frees the data referenced by |bn| and, if |bn| was originally
  /// // allocated on the heap, frees |bn| also.
  void BN_free(
    ffi.Pointer<BIGNUM> bn,
  ) {
    return _BN_free(
      bn,
    );
  }
```

The comments copying includes the `//`'s which were already in the C source. Would it be possible to detect and remove these?

**Comment by mannprerak2** [comment]
https://github.com/dart-lang/ffigen/blob/02244360d5c0f28132062ac1de215cd48bc6d7b4/lib/src/header_parser/utils.dart#L189-L190

We don't remove `//` from full comments currently. but we should probably add this.
