### ISSUE TITLE
pass in compiler-opts on commandline

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#189]
Depending on host OS and installed toolchains we need to pass in different compiler options to make various ffigen invocations work.

Instead of adding all individual versions to the `yaml` configuration, it might make sense to allow passing these options in to the ffigen invocation.

Instead of

```yaml
compiler-opts: '-I/usr/local/opt/llvm/lib/clang/11.1.0/include/' # 11.1.0 might be some other version
```

write a script

```dart
import 'dart:io';

void main(List<String> arguments) {
  final headers = headerPaths();
  final root =
      Directory.fromUri(Platform.script).parent.parent.uri.toFilePath();
  final result = Process.runSync('dart', [
    'run',
    'ffigen',
    '--config=$root/bin/ffigen.yaml',
    ...headers, // This is currently not supporteed
  ]);
}

List<String> headerPaths() {
  if (Platform.isMacOS) {
    const brewLlvmPath = "/usr/local/opt/llvm/lib/clang";
    final result = Process.runSync('ls', [brewLlvmPath]);
    final stdout = result.stdout as String;
    if (stdout == "") {
      print("The stdlib headers could not be found.");
      print("Please run `brew install llvm`.");
      exit(1);
    }

    // We pick the first available one.
    final version = stdout.split("\n").first;

    final path = "$brewLlvmPath/$version/include";
    final include = "-I$path";
    return [include];
  }
  throw UnsupportedError("Unknown operating system");
}
```

(Without providing headers `stdarg.h` and other headers from the standard library cannot be found by clang on various project.)

Maybe we should interpret all arguments that we don't consume as `compiler-opts`.

**Comment by mannprerak2** [comment]
> Maybe we should interpret all arguments that we don't consume as compiler-opts.

How about we create a new cmd line option for this? E.g -
```bash
dart run ffigen --config ffigen.yaml --compiler-opts "-I/usr/lib/include -L/usr/lib -W -Wno-nullability-completeness"
```

The only difference is that users need to enclose the compiler-opts in quotes. 
> I found this easier to implement in code, `pacakge:args` doesn't seem to allow unknown options with all the other nice features.

**Comment by dcharkes** [comment]
sgtm
