### ISSUE TITLE
How to allocate ffi.struct?

### ISSUE THREAD

**Issue by monkeyWie** [dart-lang/ffigen#197]
Hello, I used ffigen to gen code like this:
```
class Options extends ffi.Struct {
  external ffi.Pointer<ffi.Int8> name;

  external ffi.Pointer<ffi.Int8> path;

  @ffi.Int32()
  external int connections;
}
```

but I can't get or set value to it, it will occur segmentation fault:
```
var opt = Options();
print(opt.connections);

//Segmentation fault
```

**Comment by mannprerak2** [comment]
You need to use `malloc` (or `calloc`) from `package:ffi` to allocate a struct.

```dart
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart' as pkgffi;

class Options extends ffi.Struct {
  external ffi.Pointer<ffi.Int8> name;

  external ffi.Pointer<ffi.Int8> path;

  @ffi.Int32()
  external int connections;
}

void main() {
  ffi.Pointer<Options> ptr = pkgffi.malloc<Options>();

  Options struct = ptr.ref;
}
```

**Comment by mannprerak2** [comment]
Maybe we should generate a private constructor `._()`, so that users cannot instantiate a Struct using the default constructor. 
Wdyt? @dcharkes

**Comment by monkeyWie** [comment]
@mannprerak2 Thanks!

**Comment by dcharkes** [comment]
> Maybe we should generate a private constructor `._()`, so that users cannot instantiate a Struct using the default constructor.
> Wdyt? @dcharkes

Tracking this here: https://github.com/dart-lang/sdk/issues/44987
