### ISSUE TITLE
Duplicate class and function name

### ISSUE THREAD

**Issue by budius** [dart-lang/ffigen#199]
I was trying to use Wireguard from Dart using this https://git.zx2c4.com/wireguard-tools/tree/contrib/embeddable-wg-library

But the generated output gave both a function and a class with the same name.
There was the function:
```
  ffi.Pointer<if_nameindex> if_nameindex() {
    return _if_nameindex();
  }
```
and the class
```
class if_nameindex extends ffi.Struct {
  @ffi.Uint32()
  external int if_index;

  external ffi.Pointer<ffi.Int8> if_name;
}
```

Which leads to the error that "if_nameindex isn't a type".
To fix it I had to manually rename the class to `class IfNameIndex` and it's references.

Should this be automatically handled by `ffigen`?
I saw the rename option in the docs, but couldn't figure out if that would work, maybe some better doc there?

**Comment by mannprerak2** [comment]
Hi @budius, thanks for filing this bug.

> Should this be automatically handled by ffigen?

Yes, it should have.  I'll add a fix for this as soon.

You can rename the struct as a workaround for now -
```yaml
  structs:
    rename:
      'if_nameindex': 'IfNameIndex'
```

**Comment by budius** [comment]
> > Should this be automatically handled by ffigen?
> 
> Yes, it should have. I'll add a fix for this as soon.
>

I added the workaround and works perfectly.
Thanks a o lot for the super quick reply.
