### ISSUE TITLE
Clarify C++ support 

### ISSUE THREAD

**Issue by derolf** [dart-lang/ffigen#208]
I tried to run ffigen on some mixed c/c++ codebase to extract the c-bindings.

I got very wild errors and apparently ffigen just doesn’t support c++ headers (yet). Can you please clarify this?

**Comment by mannprerak2** [comment]
Hi @derolf 
Neither ffigen, nor `dart:ffi` supports C++ as of now (See https://github.com/dart-lang/sdk/issues/42210).

You should run ffigen on `.h` files that are valid C source, and can be parsed by a C compiler (i.e something you can #include in a C project will work with ffigen).

If you own the codebase, It's possible that you have a C++ project and are using `extern "C"` to specify which functions should be exposed in the headers. For those header files you can make them compatible with C like this -

```C
#ifdef __cplusplus
extern "C" {
#endif

... // body of header

#ifdef __cplusplus
} // closing brace for extern "C"

#endif
```

**Comment by derolf** [comment]
I understand that, but it would be nice to put this in the README...
