### ISSUE TITLE
Add `ignore_for_file` comments to head to avoid messages by analyzer

### ISSUE THREAD

**Issue by Fox32** [dart-lang/ffigen#211]
The analyzer complains about `unused_field` and `unused_element` for my generated file. One might configure ffigen to only output definitions that are realy used, but I guess most people will just use the generated code as-is. Therefore the generated file could contain statements that disable these lints for the specific file. This can be done by including comments at the top of the file:

```dart
// ignore_for_file: unused_field
// ignore_for_file: unused_element
```

It is possible to configure a `preamble`, so my current workaround is to include this configuration:

```yaml
preamble: |
  // ignore_for_file: unused_field
  // ignore_for_file: unused_element
```

Implementation would probably be [here](https://github.com/dart-lang/ffigen/blob/master/lib/src/code_generator/writer.dart#L162).

**Comment by mannprerak2** [comment]
The preamble was really meant for this purpose (Adding lint ignores, license headers, etc).

I don't think we should handle all possible lint warnings, since that would probably require `analyzer` as a dependency.

We can probably add a default value for preamble -
```
// ignore_for_file: unused_field
// ignore_for_file: unused_element
```
so users can override the preamble if they'd like.

cc @dcharkes

**Comment by dcharkes** [comment]
Yes, the preamble is meant for this.

I prefer to not add a default:
1. It would create weird behavior when people add their own preamble and it does not contain it.
2. Some people might not create a preamble and use the lints for seeing whether they include the right list of symbols.

**Comment by Fox32** [comment]
Sure, that makes sense - `preamble` works fine. I wonder if we want to update the documentation. The default value currently reference the header that is always added to the file anyway. Maybe `ignore_for_file` would be a better example? Beside that, I think we can close this ticket.
