### ISSUE TITLE
Generating Unions

### ISSUE THREAD

**Issue by chrisnorman7** [dart-lang/ffigen#214]
Hi,
I apologise if there is already an issue for this, but either Google isn't being helpful, or I don't understand enough of the terminology to know what I'm looking at.

I'm in the process of trying to write bindings for [SDL](https://github.com/chrisnorman7/dart_sdl), and I'm running into issues.

SDL uses a union [SDL_Event](https://wiki.libsdl.org/SDL_Event), and obviously ffigen isn't generating it.

From my research, it seems as though Union support is coming, but certainly hasn't filtered down to 2.13 as of yet. Is this true? Is there a way I can test the latest ffigen if I switch to Flutter Master?

Thanks in advance.

**Comment by mannprerak2** [comment]
The latest version of ffigen doesn't support generating unions as of now.

I think we should probably wait till a beta (or atleast the next dev) dart sdk is released before we add support for generating unions.

cc @dcharkes

**Comment by chrisnorman7** [comment]
OK, thank you for the info.

Is there a way I can manually bind them as of now? I'm not sure I know
enough C to pull it off, but I'd be willing to give it a go.

Thanks in advance.

Take care,

Chris Norman

**Comment by dcharkes** [comment]
The last dev release, `2.14.0-90.0.dev`, contains support for unions (with a [bug](https://github.com/dart-lang/sdk/issues/45988) though, so we might want to wait until the next dev release).

(Side note, we might want to wait with merging support for unions until after 2.13 stable comes out and we do a release for Dart 2.13 with packed structs etc. swapping to Dart stable and then after that land this swapping to Dart dev again.)

**Comment by mannprerak2** [comment]
Hi, @chrisnorman7 I've added a draft PR for union support, not sure when we'll merge it though.

Until then you are welcome to use a git dependency to test it out. If you find any bugs, please do let us know.

**Comment by chrisnorman7** [comment]
Hi,
That's great work, thank you.

I've had a brief look, but didn't see any docs for using it. Am I being
stupid? How does one use these unions?

Thanks for all your help, it's very much appreciated.

Take care,

Chris Norman

**Comment by mannprerak2** [comment]
@chrisnorman7  Just regenerate the bindings using ffigen from the PR branch and ffigen will generate the unions (if any in your source).
You can include/exclude/rename/rename-members exactly like structs.

**Comment by chrisnorman7** [comment]
Thank you. I got them generated, and all that is working great.

I suppose I'm a bit confused as to how to use them once I've got them in
dart. This could well be a hole in my understanding of what unions do in C,
but I'm unsure if I'm supposed to do `if (u.member == null) for each
member, or something else?

Honestly, if this is covered elsewhere on the net, please just say. I am
more than happy to Google, I don't want to waste your time.

Take care,

Chris Norman

**Comment by mannprerak2** [comment]
Yeah, you should probably check out how unions work in C.

**Comment by chrisnorman7** [comment]
OK, no problem. Thank you so much.

Take care,

Chris Norman

**Comment by dcharkes** [comment]
@chrisnorman7 you can now depend on the prerelease from pub: https://pub.dev/packages/ffigen/versions/3.1.0-dev.0

**Comment by chrisnorman7** [comment]
Lovely, thank you so much.

Take care,

Chris Norman
