### ISSUE TITLE
Typedef support

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/ffigen#217]
Now that Dart 2.13 has non-function typedef support I think it would be reasonable to translate C typedefs to Dart typedefs. In a library I'm attempting to wrap it has a lot of simple typedefs, which makes it hard when I'm trying to find some type under a certain name as specified in the headers, only to find it has a different name in the dart library generated by ffigen.

**Comment by mannprerak2** [comment]
Yes, this would be a good feature, especially when structs have multiple names. We should still probably only generate typedefs that are being used somewhere in the generated code.

**Comment by TimWhiting** [comment]
I think that only generating typedefs that are being used somewhere is a good default, but the option to include all typedefs should be available.

**Comment by mannprerak2** [comment]
From what I see, having typedefs that aren't being used anywhere in the generated bindings would be useless, even if generated. 

Can you point out some use cases for when this would be helpful? Otherwise simply generating the typedefs would be much simpler.

**Comment by TimWhiting** [comment]
I guess you are right. I can't think of a situation where that would be useful
