### ISSUE TITLE
[Feature] Config to expose native-type/dart-type of functions

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#226]
# Background

[My `getNativeSystemInfo`](https://github.com/Sunbreak/dynamic_load.trial/blob/552f0d23c41f97137f5174d5c36024c5cff53471/example/GetNativeSystemInfo.dart#L34-L49) is inspired by [`win32` example](https://github.com/timsneath/win32/blob/main/example/dynamic_load.dart)

```dart
typedef getNativeSystemInfoNative = Void Function(
    Pointer<SYSTEM_INFO> lpSystemInfo);
typedef getNativeSystemInfoDart = void Function(
    Pointer<SYSTEM_INFO> lpSystemInfo);

void getNativeSystemInfo(Pointer<SYSTEM_INFO> lpSystemInfo) {
  final pGetNativeSystemInfo =
      getFuncAddress('kernel32.dll', 'GetNativeSystemInfo');

  final funcGetNativeSystemInfo =
      Pointer<NativeFunction<getNativeSystemInfoNative>>.fromAddress(
              pGetNativeSystemInfo)
          .asFunction<getNativeSystemInfoDart>();

  funcGetNativeSystemInfo(lpSystemInfo);
}
```

And I'd like to call `NtQuerySystemInformation`: https://github.com/Sunbreak/dynamic_load.trial/blob/552f0d23c41f97137f5174d5c36024c5cff53471/example/NtQuerySystemInformation.dart

```dart
    final funcNtQuerySystemInformation =
        Pointer<NativeFunction<c_NtQuerySystemInformation>>.fromAddress(
                pNtQuerySystemInformation)
            .asFunction<dart_NtQuerySystemInformation>();
```

# Problem

`pub run ffigen --config example\ntdll\winternl.yaml` results in private `typedef`s

```dart
typedef _c_NtQuerySystemInformation = ffi.Int32 Function(
  ffi.Int32 SystemInformationClass,
  ffi.Pointer<ffi.Void> SystemInformation,
  ffi.Uint32 SystemInformationLength,
  ffi.Pointer<ffi.Uint32> ReturnLength,
);

typedef _dart_NtQuerySystemInformation = int Function(
  int SystemInformationClass,
  ffi.Pointer<ffi.Void> SystemInformation,
  int SystemInformationLength,
  ffi.Pointer<ffi.Uint32> ReturnLength,
);
```

# Request

Add config to exposure the meta type of functions

```yaml
functions:
  public-meta-type: true
```

**Comment by dcharkes** [comment]
Shouldn't this be called `dart-type` rather than `meta-type`?

We should probably have users specify a pattern of which functions they want Dart signatures for:

```yaml
functions:
  dart-typedef:
    include:
      - '.*'
```

**Comment by Sunbreak** [comment]
> Shouldn't this be called `dart-type` rather than `meta-type`?

`native-type` and `dart-type` are both needed. I don't think it a good idea to expose `native-type` with `symbol-address` -- it works for another purpose

**Comment by dcharkes** [comment]
Maybe we should add a `native-typedef` as well, and `symbol-address` implies `native-typedef`?

Meta means something different. A meta-type is a type describing a type. Just like meta communication is communicating about communication. (Off-topic: the whole ffigen package is full of meta types! 🚀 )

**Comment by mannprerak2** [comment]
> Maybe we should add a native-typedef as well

Yes, If we want to expose the dart type, we should separate `native-typedef` from `symbol-address`. Another option is to also expose the dart typedef if symbol-address is specified.
1. `3` separate configs - `symbol-address`, `native-typedef` , `dart-typedef`. (This is more verbose)
2. `1` config -  `symbol-address` exposes all 3 => function pointer, native typedef and dart typedef.

I don't have any preference here. @dcharkes it's your call.

**Comment by dcharkes** [comment]
Depends on the use case.

@Sunbreak does your use case just involve using the Dart signatures? Or do you also use the C signatures and the symbol addresses?

**Comment by Sunbreak** [comment]
> Depends on the use case.
> 
> @Sunbreak does your use case just involve using the Dart signatures? Or do you also use the C signatures and the symbol addresses?

[`Using Run-Time Dynamic Linking`](https://docs.microsoft.com/en-us/windows/win32/dlls/using-run-time-dynamic-linking) needs both Dart signatures and C signatures, but not the symbol addresses

https://github.com/Sunbreak/dynamic_load.trial/blob/552f0d23c41f97137f5174d5c36024c5cff53471/example/NtQuerySystemInformation.dart

```dart
    final funcNtQuerySystemInformation =
        Pointer<NativeFunction<c_NtQuerySystemInformation>>.fromAddress(
                pNtQuerySystemInformation)
            .asFunction<dart_NtQuerySystemInformation>();
```

**Comment by dcharkes** [comment]
Available in https://pub.dev/packages/ffigen/versions/4.0.0-dev.2

**Comment by Sunbreak** [comment]
> Available in https://pub.dev/packages/ffigen/versions/4.0.0-dev.2

Works like a charm! https://github.com/Sunbreak/dynamic_load.trial/blob/56953bb6e0b5d4badffb13bf3446cd794c914d26/example/ntdll/winternl.dart#L14-L17

```dart
  return ffi.Pointer<
              ffi.NativeFunction<NativeNtQuerySystemInformation>>.fromAddress(
          pNtQuerySystemInformation)
      .asFunction<DartNtQuerySystemInformation>();
```
