### ISSUE TITLE
Fail to define constants for `NTSTATUS` on Windows

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#227]
# Description

When generate `ntstatus.h`, `NTSTATUS` macros are missing

```c
// It works
#define FACILITY_DEBUGGER                0x1

// It doesn't
#define STATUS_INVALID_INFO_CLASS        ((NTSTATUS)0xC0000003L)
```

```dart
// Available
const int FACILITY_DEBUGGER = 1;

// Unavailable
// const int STATUS_INFO_LENGTH_MISMATCH = 0xC0000004 | 0xFFFFFFFF00000000;
```

# Reproduce

Example: https://github.com/Sunbreak/dynamic_load.trial/tree/3d4a4f74f2f799ba5e77fa729016ffdd71a9621f/example/ntstatus
 
After `pub run ffigen --config example\ntstatus\ntstatus.yaml`

`_ntstatus.dart` contains `FACILITY_*` constants but no `STATUS_*` constants

**Comment by mannprerak2** [comment]
Can you shed some light on how `((NTSTATUS)0xC0000003L)` expands? 

Macros are not accessible in libclang. The way we handle them is by creating a variable using them in C++ and then evaluating it's value.

```C++
auto a = STATUS_INVALID_INFO_CLASS;
```

If this statement is invalid (depends on how the macro expands), the macro will not be generated.

**Comment by Sunbreak** [comment]
`NTSTATUS` is basically a `LONG`

```c
#ifndef _NTDEF_
typedef _Return_type_success_(return >= 0) LONG NTSTATUS;
typedef NTSTATUS *PNTSTATUS;
#endif
```

---

Does `ffigen` support `#define STATUS_INVALID_INFO_CLASS        ((LONG)0xC0000003L)` to `const int STATUS_INFO_LENGTH_MISMATCH = 0xC0000004;`?

**Comment by mannprerak2** [comment]
I think the definition for `NTSTATUS` might be missing from the include headers.

If you add `typedef long NTSTATUS` at the top, ffigen generates this (decimal) -
```dart
const int STATUS_INFO_LENGTH_MISMATCH = 3221225476;
```

**Comment by Sunbreak** [comment]
Thanks a lot. I fix the `NTSTATUS` with a `#include <Windows.h>`: https://github.com/Sunbreak/dynamic_load.trial/commit/681907f680f6823ae0a7a4c63265fcf9e80c54bb
