### ISSUE TITLE
How to transform ffi.Array<Uint8> to ffi.Point<Uint8>?????

### ISSUE THREAD

**Issue by fayfive** [dart-lang/ffigen#245]
How to transform
@ffi.Array.multi([8])
external ffi.Array<ffi.Pointer<ffi.Uint8>> data;
 to
ffi.Pointer<ffi.Pointer<ffi.Uint8>> data

**Comment by dcharkes** [comment]
duplicate of https://github.com/dart-lang/ffi/issues/117
