### ISSUE TITLE
test/debug_generated/README.md

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#248]
```
Package validation found the following potential issue:
* 1 checked in file is ignored by a `.gitignore`.
  Previous versions of Pub would include those in the published package.
  
  Consider adjusting your `.gitignore` files to not ignore those files, and if you do not wish to
  publish these files use `.pubignore`. See also dart.dev/go/pubignore
  
  Files that are checked in while gitignored:
  
  test/debug_generated/README.md
```

Not urgent, but we should probably clean it up.

Possibly just remove this file (which removes the folder in git) and then make sure that the tests will create the folder if they try to write here.

**Comment by mannprerak2** [comment]
This gitignore specifies this file to not be excluded explicitly, so this warning doesn't really make sense to me -
 ```
# Files generated by tests for debugging purposes.
test/debug_generated/*
!test/debug_generated/readme.md
```

> make sure that the tests will create the folder if they try to write here.

But, yes, we should still do this.
