### ISSUE TITLE
error running ffigen on apple silicon

### ISSUE THREAD

**Issue by maks** [dart-lang/ffigen#260]
On a M1 macmini I followed the readme instructions to have Xcode and llvm installed via homebrew (`brew install llvm`)

But trying to run I get:
```
% flutter pub run ffigen
Running in Directory: '/Users/maks/'
[WARNING]: Prefer adding Key '[description]' to your config.
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/opt/homebrew/opt/llvm/lib/libclang.dylib': dlopen(/opt/homebrew/opt/llvm/lib/libclang.dylib, 0x0001): tried: '/opt/homebrew/opt/llvm/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libclang.dylib' (no such file), '/opt/homebrew/Cellar/llvm/13.0.0_2/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libclang.dylib' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      initializeGlobals (package:ffigen/src/header_parser/data.dart:41:33)
#3      initParser (package:ffigen/src/header_parser/parser.dart:48:3)
#4      parse (package:ffigen/src/header_parser/parser.dart:22:3)
#5      main (package:ffigen/src/executables/ffigen.dart:54:19)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

So I guess I need to have a x86_64 version of llvm installed via homebrew? Or can I instead use a aarch64 build of the Dart SDK which I think is now available? Or will that not work given I'm running ffigen to generate a binding in a Flutter plugin?
Versions:
```
flutter --version
Flutter 2.9.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f1f9c10f0 (7 days ago) • 2021-12-14 13:41:48 -0800
Engine • revision 234aca678a
Tools • Dart 2.16.0 (build 2.16.0-80.1.beta) • DevTools 2.9.1
```

**Comment by maks** [comment]
As a followup, [per the instructions in this article](https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f), I installed x86 homebrew and hence x86 llvm, luckily they use different paths and can be installed alongside each other, then setting ffigen's `llvm-path` in my pubspec to point to the x86 llvm install then has ffigen working fine:
```
llvm-path:
    # use on MacOS AppleSilicon to use x86 version of llvm
    - "/usr/local/homebrew/opt/llvm"
 ```

Maybe this could be added to ffigen's readme for future reference?

**Comment by dcharkes** [comment]
It sounds like you're running dart in x64 mode instead of arm64. Can you confirm with `dart --version`?

How did you install/download the Dart SDK?

The arm64 MacOS Dart SDK is available on the download page: https://dart.dev/get-dart/archive.

**Comment by maks** [comment]
@dcharkes yes I think that is whats happening. I get:
```
dart --version
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_arm64"
```
which I checking seems to reveal I installed via homebrew:
```
which dart
/opt/homebrew/bin/dart
```
But trying to update it revealed that the terminal inside VSCode that I was using seems to be running under Rosetta itself:
```
brew upgrade dart
[snip]...
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
```

So I then used a different terminal, ssh'ing into the macmini, which got me a arm (not rosetta) shell, but then because I have my ffigen inside a Flutter plugin package, when I try to use the arm64 Dart sdk installed via arm64 homebrew I get:
```
dart run ffigen 
The Flutter SDK is not available.
#0      BoundSdkSource.getDirectory (package:pub/src/source/sdk.dart:123:7)
#1      SystemCache.load (package:pub/src/system_cache.dart:113:52)
#2      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:
...
```

So I guess this will all just work once Flutter starts shipping a arm64 build of Dart inside the Flutter SDK?

**Comment by dcharkes** [comment]
Ah correct, only Dart standalone supports arm64 MacOS. The Flutter SDK does not yet natively: https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon
