### ISSUE TITLE
Analysis error in 4.1.2.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#265]
https://pub.dev/packages/ffigen/versions/4.1.2/score

```
$ dart analyze lib/src/header_parser/sub_parsers/compounddecl_parser.dart
Analyzing compounddecl_parser.dart...  2.5s

  error • compounddecl_parser.dart:196:9 • Argument 'exceptionalReturn' must be a constant. Try replacing the value with a literal or const. • argument_must_be_a_constant

1 issue found.
```

We've already fixed this in the 5.0.0 pre-release:
https://pub.dev/packages/ffigen/versions/5.0.0-dev.0/score

We could make a 4.1.3 release to patch this. wdyt @mannprerak2? Worth making a new version for?

They failing analysis could be the cause for [Unidentified] as a label on the package.
![image](https://user-images.githubusercontent.com/3601775/151988620-3a5ed2d8-8949-4657-b531-4a0ac0edbc8b.png)

cc @jonasfj

**Comment by mannprerak2** [comment]
Yeah I think we should fix this. I'll try and make a PR today.

**Comment by dcharkes** [comment]
![image](https://user-images.githubusercontent.com/3601775/152375447-b4f7116f-4842-42ba-8154-e874d2fee2f7.png)
