### ISSUE TITLE
Couldn't find dynamic library in default locations in macOS 

### ISSUE THREAD

**Issue by dongzhenggang123** [dart-lang/ffigen#277]
I get this error 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/13194532/154922331-e8e988b8-aa56-4404-9dfd-9d0133ebff0c.png">

this is my yaml info, I don't know if llvm path is wrong
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/13194532/154922168-3e62078c-a398-407a-9eaa-0d302b5dfbe9.png">

**Comment by mannprerak2** [comment]
You need to install llvm (The one bundled with the OS will probably not work). See https://github.com/dart-lang/ffigen#using-this-package
You can then supply it under llvm-path, if it installs it under a different location.
