### ISSUE TITLE
Clean up: make Type polymorphic

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#284]
It looks like `Type` is a thin wrapper around a lot of different kinds of type, each with a different implementation class. The `BroadType` says which kind of type it is, and each one has a nullable field containing the implementation. So we end up with a lot of switches and ifs on the `BroadType`, and then a lot of null check `!` operators to access the implementation. For example, if `Type.broadType` is `BroadType.Enum`, it means `Type.enumClass` should be non-null.

A simpler approach might be for `Type` to be an interface, and each of the different kinds of type would just implement this interface. Then the `BroadType` checks would change to `type is EnumClass`, and the switches would just be polymorphic method calls. There is already a base class for all the implementations like `EnumClass`, called `Binding`, so maybe `Type` could be a subclass of `NoLookupBinding`?

**Comment by mannprerak2** [comment]
Sound fine to be.

`Type` probably cannot be a subclass of `NoLookupBinding`, since a binding object is equivalent to a declaration, while Type also contains `Pointer` which is inline.

**Comment by liamappelbe** [comment]
Oh yeah, that makes sense. I guess `Type` should just be a pure interface that `EnumClass` etc implement. So it would be parallel to the `Binding` inheritance tree.
