### ISSUE TITLE
User friendly bindings for NSString

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#295]
Come up with a user friendly API that looks similar to [the official one](https://developer.apple.com/documentation/foundation/nsstring?language=objc) and handles converting to and from Dart strings

**Comment by liamappelbe** [comment]
cc @brianquinlan

**Comment by dcharkes** [comment]
You could consider adding extension methods, similar to how we do `String` <-> `Pointer<Utf8>` in `package:ffi`.

https://github.com/dart-lang/ffi/blob/master/lib/src/utf8.dart
