### ISSUE TITLE
ObjC memory management

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#305]
First pass: expose the manual reference counting methods.
Later: use Dart finalizers to automatically call these methods.

**Comment by dcharkes** [comment]
`NativeFinalizer` is available in Dart in `2.17.0-266.0.dev` and from Dart 2.17 stable.

**Comment by liamappelbe** [comment]
Do you think I need to support the manual reference counting case, or can we just set the minimum Dart version to 2.17 for objective C interop? It would be nice to only have to support one mode, but I'm not sure if that's going to be too restrictive on the Dart version.

**Comment by mannprerak2** [comment]
I think we should go with minimum 2.17, we also need to phase out package:ffi dependency and yse ABI specific integers types from 2.17.

**Comment by dcharkes** [comment]
Agreed. Let's target 2.17 stable. Feel free to bump the min SDK to `2.17.0-266.0.dev` in the mean time.

**Comment by brianquinlan** [comment]
Probably you want something like:
```dart
class _ObjCWrapper implements ffi.Finalizable {
  _ObjCWrapper._(this._id, this._lib, {bool retain = false}) {
    if (retain) {
       // call retain
    }
    objcReleaseFinalizer.attach(this, this._id, detach: this);
  }
}

final stdlib = ffi.DynamicLibrary.process();
typedef PosixFreeNative = ffi.Void Function(ffi.Pointer<ffi.Void>);
final objc_release =
    stdlib.lookup<ffi.NativeFunction<PosixFreeNative>>('objc_release');
final objcReleaseFinalizer = ffi.NativeFinalizer(objc_release);
```
