### ISSUE TITLE
ObjC: objc_interface _builtInFunctions is global and stateful

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/ffigen#324]
[`_builtInFunctions`](https://github.com/dart-lang/ffigen/blob/master/lib/src/code_generator/objc_interface.dart#L137) in `objc_interface.dart` is global and maintains state about the generation of the current bindings.

This means that more than one binding cannot be generated cannot be generated without restarting the process.

**Comment by liamappelbe** [comment]
ffigen has a bunch of global objects. The others are all defined in data.dart, and are reset by `initializeGlobals`, so we just need to move this object there.
