### ISSUE TITLE
Remove goldens for platform dependent tests

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#362]
Our ObjC tests that verify that the output matches a golden can only be regenerated on mac devices. This makes it [hard to contribute](https://github.com/dart-lang/ffigen/issues/7#issuecomment-1124271285) from non-mac devices. These tests aren't super necessary anymore either, since we have good integration test coverage of our ObjC features, in native_objc_test. So we should probably just remove them.

I'm not sure that all the C features are fully covered by integration tests, so we should keep those goldens. I'm only proposing removing the ObjC ones, because those are the ones that are platform dependent.

**Comment by dcharkes** [comment]
> I'm not sure that all the C features are fully covered by integration tests, so we should keep those goldens.

Integration tests do not cover all ABIs. For example we run the tests only on 64 bit platforms, so if we emit the wrong integer type that happens to be correct on all 64 bit platforms we would miss that.

I can see how having the ObjectiveC tests only being able to run on MacOS is problematic. So, having no goldens for ObjectiveC but keeping them for C sounds like a good compromise to me. 👍 

cc @mannprerak2.
