### ISSUE TITLE
Release 5.0.0 stable that targets ABI-specific types in Dart 2.17

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#364]
We should release a new version of ffigen that targets the ABI-specific types in `dart:ffi` now that Dart 2.17 has been released.

cc @mannprerak2 or @simolus3 can you make a PR for this?

- [x] target ABI-specific ints in `dart:ffi` (and no longer `package:ffi` at all?)
- [x] update pubspec to target 2.17 and bump the version number to 5.0.0
- [ ] https://github.com/dart-lang/ffigen/issues/236 could be included, but we can also do it in 5.1.0
- [x] https://github.com/dart-lang/ffi/pull/141 depend on a newer version than the package:ffi dev release.

@liamappelbe @brianquinlan ObjectiveC checklist

- [x] Do we have documentation on the ObjectiveC features that they are (bold & caps) experimental and that they can change at any time. Both in the readme and as a severe log when using the feature?
- [x] Anything we should be aware of before making a 5.0.0 stable release?

Super cool to have experimental ObjectiveC support in the next release! (Prepare for user bug reports! 🎉 )

Maybe we can make a release tonight or tomorrow.

**Comment by dcharkes** [comment]
Now that Dart 2.17 is out, can we use the types from `dart:ffi` directly? (I was trying to contribute a fix, but most of the generated libraries in `test/` only generate correctly on a macOS libc so I'm out of luck)

_Originally posted by @simolus3 in https://github.com/dart-lang/ffigen/issues/7#issuecomment-1124271285_

@simolus3 can you make a PR if we remove the goldens from ObjectiveC?

* https://github.com/dart-lang/ffigen/pull/363

**Comment by simolus3** [comment]
I can get a PR ready for using `dart:ffi` ABI-specific integer types and bumping the pubspec version later today if it helps.

**Comment by simolus3** [comment]
I've opened https://github.com/dart-lang/ffigen/pull/365. Before 5.0.0 is released, perhaps version 1.2.0 of `package:ffi` should be released as well (so that this package doesn't have to depend on a pre-release version of it).

@dcharkes I can open a PR to replace the ABI-specific types from `package:ffi` with typedefs pointing towards the new type in `dart:ffi`, but I wonder if it makes sense to just remove them from `package:ffi` entirely?

**Comment by dcharkes** [comment]
Can't we revert back to 1.1.2? 1.2.0 contained the ABI-specific types that we decided should be in `dart:ffi` instead.

Yes, the goal is to release a version of package:ffi without the ABI-specific types, but that is already out there 1.1.2. It is just confusing that we don't have a newer version released.

**Comment by dcharkes** [comment]
> > * [ ]   Anything we should be aware of before making a 5.0.0 stable release?
> 
> I think the biggest missing feature from the ObjC support is that there's no memory management atm. We just leak all created objects. But I suppose that's ok for an experimental feature.

@liamappelbe Would you like more disclaimers in the README and/or logs when using it? Or can I go ahead and release 5.0.0 ?

**Comment by liamappelbe** [comment]
I think the current disclaimers are good. You can release.

**Comment by dcharkes** [comment]
https://pub.dev/packages/ffigen/versions/5.0.0

Thanks @liamappelbe @brianquinlan @simolus3 @mannprerak2 for your contributions! 🚀
