### ISSUE TITLE
#363 caused the coverage total to drop a lot

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#369]
Now that all the ObjC code gen is done in `test/setup.dart`, these parts are not covered by tests, so the coverage total doesn't include them.

One possible fix is to restore the parts of the tests that invoked the code generator during the test.

**Comment by dcharkes** [comment]
Wait, we need to run the setup in the setup? I guess we run it in a separate step in which the coverage is not running.

Doesn't the test framework have a 'setup' phase where we could do the code generation?

**Comment by dcharkes** [comment]
Can we run the generator in the pre-coverage step. And then run the generator in a test again but generate to a different folder so it doesn't interfere with running the other tests? It's not efficient, but it gives us the coverage back.
