### ISSUE TITLE
Support for generating comments sqlite3

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#38]
We talked about supporting non-doc-string comments, we should implement it.

**Comment by dcharkes** [comment]
```yaml
compiler-opts: "-fparse-all-comments"
comments: 'full'
```

This works.

But, I think we should have an option in the yaml to do this, rather than having to specify the compiler option in the yaml.

**Comment by mannprerak2** [comment]
We can have the following options - 
```yaml
comments: [none | doc-brief | doc-full | any-brief | any-full]
```
- `doc` will only parse doxygen style comments & `any` will parse any comment.
- `brief` only gives us the first paragraph and performs a simple wrap, `full` takes the full comment as it is and does not wrapping.

**Comment by dcharkes** [comment]
Maybe call it `doxygen` instead of `doc` for clarity.

We can also make two options:

```
comments:
  style: doxygen-only | all
  length: none | brief | full
```

Any reason to not go for all-full as default? (Any header files where that generates horribly wrong things?)

**Comment by mannprerak2** [comment]
> Any reason to not go for all-full as default? (Any header files where that...

Nope, just the thing that we don't do wrapping on full comments (as the simple wrapping we perform may distort code samples or something else) can generate really long lines of comments if the C API comments aren't formatted well.
This is evident from [our cJSON example](https://github.com/dart-lang/ffigen/blob/master/third_party/cjson_library/cJSON.h#L150), where if we generate full comments would cause this.

**Comment by dcharkes** [comment]
> Nope, just the thing that we don't do wrapping on full comments (as the simple wrapping we perform may distort code samples or something else) can generate really long lines of comments if the C API comments aren't formatted well.
This is evident from our cJSON example, where if we generate full comments would cause this.

Well, then there's an argument for both as default, pick whatever you prefer. 😄
