### ISSUE TITLE
ffigen tries to write tmp files to working directory

### ISSUE THREAD

**Issue by thomas725** [dart-lang/ffigen#400]
When the header declared as entry-point in the config file passed contains #define constants, ffigen tries to write a temp file named `temp_for_macros.hpp` to the current working directory.

Since I've been calling ffigen from / = root to workaround https://github.com/dart-lang/ffigen/issues/257 this failed with a permission denied error.

Could you maybe write temp files to `/tmp/` instead of `./` (=working directory)?

See also: https://github.com/fzyzcjy/flutter_rust_bridge/issues/494

**Comment by TzviPM** [comment]
To make this a bit more robust, would you be willing to implement the following:

1. Add a helper method for returning a temporary directory to use for testing.
2. Respect the environment variable `TEST_TMPDIR` if defined for compatibility with Bazel and other more complex build configurations.
3. If `TEST_TMPDIR` is not defined, then create one using `Directory.systemTemp.createTempSync()` and memoize it for use within the execution of ffigen.

I can put up a PR to illustrate this.
