### ISSUE TITLE
Is there any trick to use package:ffi in ffigen?

### ISSUE THREAD

**Issue by hawkkiller** [dart-lang/ffigen#404]
### Hello guys!
If I declare a parameter like char*, then the ffigen generates me the Pointer<Char> instead of Pointer<Utf8> and I can't operate with that char. So what should I do? Write some parts of the bindings by hand?

**Comment by liamappelbe** [comment]
I don't quite understand the issue you're having. Can you paste the function you're generating a binding for, and the output you're getting?

**Comment by hawkkiller** [comment]
Sorry, the GitHub has cut the generics off. I have a
```void hello(char* name);```
And it generates
```void hello(Pointer Char name)```

**Comment by hawkkiller** [comment]
I expect to have UTF8 to easily encode/decode into native dart strings. Is there any option with Char?

**Comment by liamappelbe** [comment]
Yeah, import `package:ffi` and use the [`Utf8Pointer`](https://pub.dev/documentation/ffi/latest/ffi/Utf8Pointer.html) extension. I think if you've got a `Pointer<Char>` you'll just need to use the [`cast`](https://api.dart.dev/stable/2.17.3/dart-ffi/Pointer/cast.html) method to get a `Pointer<Utf8>`.

**Comment by hawkkiller** [comment]
very big thanks @liamappelbe :) Did a trick for me
