### ISSUE TITLE
Unable to find wrapper.c when precompiled

### ISSUE THREAD

**Issue by simolus3** [dart-lang/ffigen#41]
I got hyped and wanted to try this, but it fails to find `wrapper.c` for me.

Pub pre-compiles packages before running them, which appears to break the `_getWrapperPath` logic. This is what I get when running `pub run ffigen`:

```
Exception: Unable to find wrapper.c file.
#0      _getWrapperPath (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/setup.dart:156:5)
#1      _platformOptions (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/setup.dart:42:18)
#2      _platformOptions (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/setup.dart:39:23)
#3      _getPlatformOptions (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/setup.dart:253:12)
#4      autoCreateDylib (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/setup.dart:100:19)
#5      main (file:///home/simon/.pub-cache/hosted/pub.dartlang.org/ffigen-0.1.1/bin/ffigen.dart:23:30)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Since it's precompiled, `Platform.script` returns `$PROJECT_DIR/.dart_tool/pub/bin/ffigen/ffigen.dart.snapshot.dart2`. So `_getWrapperPath` would return `$PROJECT_DIR/.dart_tool/pub/bin/lib/src/clang_library/wrapper.c` which obviously doesn't exist.
Maybe the tool should parse the `packages.json` file in the `.dart_tool` folder or use `Isolate.resolvePackageUri('package:ffigen/src/clang_library/$wrapperName')` to find the file?

**Comment by mannprerak2** [comment]
Hi @simolus3
I have added a PR #42 to fix this, and have used your suggestions as well 😄 
Meanwhile, you can clone this package and add it as a local dev_dependency and it should work.

**Comment by simolus3** [comment]
Awesome - thanks! I can confirm that this works by using a git dependency.

BTW, I think you could also test that locally by using 
```
dart --snapshot=ffigen.dill bin/ffigen.dart
dart ffigen.dill
```
