### ISSUE TITLE
NSDecimal error

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#411]
NSDecimal is a bitfield struct, which is not supported, so it is treated as an incomplete struct. However, this check happens after methods/functions are parsed, so the [usual check](https://github.com/dart-lang/ffigen/issues/410) that ignores functions that take/return incomplete structs doesn't work.

The best fix would probably just be to move the bitfield check earlier in the parsing.

**Comment by liamappelbe** [comment]
> However, this check happens after methods/functions are parsed

This is wrong. The issue is that NSDecimal is being used as a property. I didn't implement the incomplete struct check for properties, because you can't use an incomplete struct as a property (since the property becomes field on the class). But you can use bit fields as properties. So I just need to implement this check for properties.

**Comment by dcharkes** [comment]
For bitfields in general we might need Dart VM support, because currently we need to emit chars/uint16/uint32/uint64 structs to ensure alignment is correct.

* https://github.com/dart-lang/sdk/issues/38954#issuecomment-688214810
* https://github.com/dart-lang/ffigen/issues/84#issuecomment-683641012
