### ISSUE TITLE
libclang test failing on mac and windows bots

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#424]
https://github.com/dart-lang/ffigen/runs/7374025573?check_suite_focus=true#step:6:399

**Comment by liamappelbe** [comment]
```
            ACT 3964	  /// "\@optional". Returns zero if the cursor is not such a declaration or it
            ACT 3965	  /// is "\@required".
            EXP 3966	  /// "@optional". Returns zero if the cursor is not such a declaration or it is
            EXP 3966	  /// "@required".
```

Weird diff. The [original header](https://github.com/dart-lang/ffigen/blob/master/third_party/libclang/include/clang-c/Index.h#L4568) has the `\`, and when the libclang bindings are generated on windows and mac, they keep the `\`. But for some reason, on linux and in the test's expectation file, the `\` is being removed.

**Comment by liamappelbe** [comment]
Turns out it's libclang itself that removes the `\`. The comment string we get back from `clang_Cursor_getBriefCommentText` may or may not include the `\`, depending on the version of clang.

**Comment by liamappelbe** [comment]
Upgraded my mac to clang 14 and now I get the `\` too. So I think the fix is just to update the text expectations and update the version of clang that the linux bot installs. Anyone running the tests locally will also need to update.

**Comment by dcharkes** [comment]
For a `\`, it might be better to modify the test to accept both, rather than forcing a newer version of clang for all users.
