### ISSUE TITLE
Generated files are derivative works

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#43]
Using a code generator on a file means that the generated file is a derivative work.

We need to do the following:

- [ ] Move the committed generated files to the third_party folder (preferably next to their sources). (Yes, that means our imports are going to be a bit weird.)
- [x] Generate the same copyright string in the top of the file as was in the original file.
  - [x] Either have an option in yaml to put the copyright string,
  - [ ] Or, find a clever way to extract the first comment in a file if it's the copyright string.

@jonasfj Any suggestions for the cleanest way of using dart files from a third_party folder?

**Comment by jonasfj** [comment]
> Any suggestions for the cleanest way of using dart files from a third_party folder?

You can't, if the `third_party/` folder has to be a top-level folder, then you'll have to move the entire package into the `third_party/` folder.

All sources must exist in the `lib/` folder of the given package, otherwise the package cannot be distributed.

**Comment by mannprerak2** [comment]
> Either have an option in yaml to put the copyright string,

This is possible, We have an option called `preamble` using which we can inject anything as the file header. [See this](https://github.com/dart-lang/ffigen/blob/master/example/libclang-example/pubspec.yaml#L70)

**Comment by dcharkes** [comment]
For the folder structure we have two options then.

1) `lib/src/third_party` (Need to check if this would be okay, usually third_party is the root folder.)

2) Make Dart packages in the third_party subfolders and import them.
```
third_party/libclang/
third_party/libclang/pubspec.yaml
third_party/sqlite3/
third_party/sqlite3/pubspec.yaml
```

Please hold off implementing until we get more clarity about this. 😄

**Comment by dcharkes** [comment]
> Typically the /third_party is at root [...]
> 
> If we aren't formatting it that way, the sqlite public domain statement should be appended in the main LICENSE file, with a note about which library it applies to. Then this location would look fine to me. samples/ffi/sqlite/lib/src/third_party/sqlite3_bindings_generated.dart

@mit-mit Any preference for the two options?

**Comment by mit-mit** [comment]
@kevmoo @natebosch what do we do in other Dart builders/generators?

**Comment by kevmoo** [comment]
> @kevmoo @natebosch what do we do in other Dart builders/generators?

We punt on it. We don't add ANY copyright header.

**Comment by kevmoo** [comment]
...we used to jump through some hoops to add it. I believe @natebosch removed that logic

**Comment by natebosch** [comment]
> I believe @natebosch removed that logic

I removed something which added a hardcoded self defined header. I don't recall anything that read headers from source files and copied them.

**Comment by kevmoo** [comment]
True! It was always a manual thing for a given package
