### ISSUE TITLE
Add a swift example

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#435]
Swift support ([almost](https://github.com/dart-lang/ffigen/issues/434)) already works, building on ObjC. Add an example.

Swift command to generate the dylib and objc wrapper header:

```
swiftc -c foo.swift -emit-objc-header-path foo.h -emit-library
```

Then we can run ffigen on foo.h to get the Dart bindings.

**Comment by dcharkes** [comment]
Should we have an `language: swift` to avoid confusion?

**Comment by liamappelbe** [comment]
no, because it's not actually going to parse swift files. The user has to generate the objc file for the swift library

**Comment by liamappelbe** [comment]
Maybe in future we can add `language: swift`, and just have ffigen invoke that `swiftc` command automatically. For now tho, I want to keep things simple to land it in time for 2.18, and just have ffigen treat it as a normal objc header.
