### ISSUE TITLE
All paths should be relative to config directory

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#443]
All the relative paths in the config file should be treated as relative to the config directory. This would allow running ffigen from any directory.

This is blocking adding a test for the swift example.

**Comment by dcharkes** [comment]
sgtm

This is probably a breaking change. Are there any examples that currently work by accident that we would break?

> This is blocking adding a test for the swift example.

What is blocked? Can't the test be run from another working directory?

**Comment by liamappelbe** [comment]
I tried changing the working directory in the test, and then changing it back, and it messes up the test framework.

**Comment by liamappelbe** [comment]
> Are there any examples that currently work by accident that we would break?

A bunch of the test configs will need to be updated. But for user code, I think most people will just be running ffigen in the same directory as the config.

If this is a breaking change, I guess that means we need to do a major version bump.
