### ISSUE TITLE
swift_class_test.dart is failing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#467]
swift_class_test.dart is failing on Apple clang version 13.0.0 (clang-1300.0.29.30): https://github.com/dart-lang/ffigen/actions/runs/3154662282/jobs/5132531993

ffigen is generating many duplicate copies of `ObjectType` for this test.

**Comment by liamappelbe** [comment]
This is a pretty specific issue. The generics in the Apple APIs all use `ObjectType` as the generic type name:

```objective-c
@interface NSArray<__covariant ObjectType> : NSObject
```

Internally, the `ObjectType` is treated as a typedef, so ffigen sees a whole bunch of typedefs with identical names. Generally this isn't an issue because ffigen excludes typedefs by default, and just uses the underlying type. That was broken for a while, but fixed by #462.

Even that wasn't enough to break the tests though, since ffigen will just rename the colliding typedefs. I'm not sure why it was only swift_class_test.dart that was failing, or why this only started happening with the github mac bot clang version update. But since the issue is so specific I don't think users are going to hit it. The test is fixed and re-enabled now.

Unassigning myself since it's a low priority fix, unless a user runs into it.

**Comment by dcharkes** [comment]
Should we close the issue and reopen if it ever reappears?

**Comment by liamappelbe** [comment]
sure
