### ISSUE TITLE
How do I convert a Pointer<Char> to a Dart string 

### ISSUE THREAD

**Issue by ma19560128** [dart-lang/ffigen#498]
```
 var dllLoad = DynamicLibrary.executable();
    Pointer<Char> result = malloc();
    NativeLibrary nativeLibrary = NativeLibrary(dllLoad);
    nativeLibrary.pingLocal(result);    
```
How to convert 'result' to a Dart string

**Comment by dcharkes** [comment]
Use `package:ffi`.

https://github.com/dart-lang/ffi/blob/master/lib/src/utf8.dart

If you want ffigen to automatically do this, this is tracked by:

* https://github.com/dart-lang/ffigen/issues/488

**Comment by ma19560128** [comment]
thanks~
