### ISSUE TITLE
Support for inline arrays in structs

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#5]
Waiting on support for [inline arrays in Structs](https://github.com/dart-lang/sdk/issues/35763) in `dart:ffi`.
Currently, we generate Array helpers as a workaround (Use `array-workaround: true` to enable), this will be replaced when proper inline
array support arrives.

**Comment by Sunbreak** [comment]
[inline arrays in Structs](https://github.com/dart-lang/sdk/issues/35763) is done. Cheers!

**Comment by dcharkes** [comment]
We'll need to wait till the first [dev-release](https://dart.dev/tools/sdk/archive#dev-channel) (currently 2.13.0-59.0.dev) after [Version 2.13.0-73.0.dev](https://github.com/dart-lang/sdk/commits/dev).

**Comment by dcharkes** [comment]
This feature is available in beta now `2.13.0-211.6.beta`.

**Comment by dcharkes** [comment]
We can remove our array workaround now 👌

**Comment by mannprerak2** [comment]
I'll try to make a PR soon.

**Comment by dcharkes** [comment]
No rush, Dart 2.13 is still in beta.
