### ISSUE TITLE
Generate bindings for unnamed enums

### ISSUE THREAD

**Issue by namniav** [dart-lang/ffigen#50]
It is very common to use unnamed enum in C:
```c
enum {
  ENUM_VALUE = 1,
  ENUM_VALUE = 2,
  //...
};
```
please consider generating bindings for them.

**Comment by mannprerak2** [comment]
The only good implementation I see here is to generate a single enum, containing values of all the unnamed enums found while parsing.
So if we have 3 unnamed enums, we generate a single _big_ enum containing all the values from all the 3 enums.
And then we can provide a config option to set the name of this generated enum.

cc @dcharkes

**Comment by namniav** [comment]
What about just putting members of unnamed enums in top-level scope ? I think this is convenient and make more sense, because enums may not be related with each other and I don't have to use a same but meaningless enum's name for them all.
PS: It would be better to support adding/replaceing prefix to enum members, as mentioned in #28. 
@mannprerak2
