### ISSUE TITLE
Header-filter exclude allow full path

### ISSUE THREAD

**Issue by RdeWilde** [dart-lang/ffigen#52]
Atm one can define the header-filter excludes using the filename. Though filenames could be ambigious over different folders. Could we use full paths to exclude certain headers?

**Comment by mannprerak2** [comment]
I see,
You cannot use the full path as of now.
Well, the only reason to use filename was to improve the time complexity, comparing filename using a HashSet is efficient.
While the absolute path can definitely not be used, this could, however, be replaced with **a regexp based comparison**, but if you excessively use these regexp based filters, it would have a performance impact.

**Comment by RdeWilde** [comment]
The performance impact is not a major throwback for me. I don't generate it continiously. But I can't speak for others.

Is the regexp based comparison something I can already use, or do you mean it could be implemented in the your code?

**Comment by mannprerak2** [comment]
> do you mean it could be implemented in the your code?

Yes, you cannot use it as of now, but I will add this next week.

But If you really really just want to highjack the codebase right now, you can clone the project and change this particular function according to our needs https://github.com/dart-lang/ffigen/blob/master/lib/src/header_parser/includer.dart#L52
You can simply return `true` here for all the files you want. 😄

**Comment by mannprerak2** [comment]
@RdeWilde check out an [example of the new design here](https://github.com/dart-lang/ffigen/issues/56#issuecomment-665561783)
Will this solve the problems?
