### ISSUE TITLE
Parameter names in function pointer field types

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/ffigen#522]
context: `jnigen`'s bindings to JVM C APIs are generated by a vendored patch of jnigen. I am trying to move it to use the API or at least import the internal `src/` APIs, in the interest of reducing the vendored code.

By default ffigen doesn't generate parameter names for struct fields of function pointer types, although the field declaration can potentially include these names.

I had a clunky patch which added a separate array of these param names.

https://github.com/dart-lang/jnigen/blob/1d858c058b40d8b06735dfdd59c71afde388392b/jni/third_party/ffigen_patch_jni/lib/src/header_parser/sub_parsers/compounddecl_parser.dart#L231

https://github.com/dart-lang/jnigen/blob/1d858c058b40d8b06735dfdd59c71afde388392b/jni/third_party/ffigen_patch_jni/lib/src/header_parser/sub_parsers/compounddecl_parser.dart#L263

Is there a better implementation strategy than "keep a global list and visit all parameter nodes"? If not I will attempt to upstream this.

**Comment by dcharkes** [comment]
@mannprerak2 is probably most suited to answer that question.

**Comment by mahesh-hegde** [comment]
1. Should this handle nested function pointer declarations?

2. Should this apply to variables with global linkage as well? Particularly, we can't get parameter names from `CXType`, we need to visit the cursor of declaration itself.

Now I think there are 2 choices.

* We can change of `getCodeGenType(CXType)` to `getCodeGenType(cursor)`?

* Alternatively we can write the auxiliary visitor to modify the names of params.

cc: @mannprerak2

**Comment by mannprerak2** [comment]
> Should this handle nested function pointer declarations?

This will probably require some significant code refactoring since we'd need to change `getCodeGenType` to work with CXCursor as well as CXType (perhaps both).

The patch is only for a single level of function pointer declaration (only for struct members in their current state). A complete solution will require that refactoring though.

**Comment by mahesh-hegde** [comment]
Makes sense. I will upstream my patch and make a PR.

**Comment by mahesh-hegde** [comment]
Now I am wondering, whether this param names be actually exposed in `external ffi.Pointer<ffi.NativeFunction<...>>` declaration?

i.e

`external external ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>comparator;`

vs 

`external external ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Int a, ffi.Int b)>>comparator;`

(I need this info just be part of internal binding structures, so that I can import the API of binding types and generate some specialized JNI code. So either decision is OK for me.)

**Comment by mannprerak2** [comment]
No preference, but I think it's better to avoid if it doesn't bring much utility.

**Comment by mahesh-hegde** [comment]
I made the PR, look at changes (mostly in SQLite library) and tell what's your preference.

It makes the declarations longer, but I think param names can be useful.
