### ISSUE TITLE
C11 alignas

### ISSUE THREAD

**Issue by nielsenko** [dart-lang/ffigen#550]
With C11 you can specify alignment like:
```C
typedef struct alignas(16) x {
    uint64_t w[2];
} x_t;
```
I know that dart:ffi does not really support `alignas` either, but at least it would be nice if ffigen didn't fail with:
```
error: declaration of anonymous struct must be a definition [Parse Issue]
warning: typedef requires a name [Semantic Issue]
```
and just ignored the _attribute_ instead.

**Comment by dcharkes** [comment]
@nielsenko is that C or C++?

Plugging it in GCC to compile a C file yields the following compile error for me:

```
<source>:6:24: error: expected identifier or '(' before numeric constant
    6 | typedef struct alignas(16) x {
      |                        ^~
<source>:8:3: warning: data definition has no type or storage class
    8 | } x_t;
      |   ^~~
<source>:8:3: warning: type defaults to 'int' in declaration of 'x_t' [-Wimplicit-int]
Compiler returned: 1
```

Repro: https://godbolt.org/z/YGTEojMjW

`libclang` only does C, not C++:

* https://github.com/dart-lang/ffigen/issues/208

**Comment by nielsenko** [comment]
Sorry, I was a bit hasty.. I didn't add the include, and I need to put the `alignas` inside the struct in C, ie:
```C
#include <stdalign.h>
#include <stdint.h>

typedef struct x {
    alignas(16) uint64_t w[2];
} x_t;

int main() { return 0; }
```
The above compile with clang 14.0.3 and gcc 12.2.0. 
 
And yes, `alignas` was a C++11 thing, but it is also part of [C11](https://en.wikipedia.org/wiki/C11_(C_standard_revision)).

The above is accepted by ffigen fine enough so sorry for the misplaced issue. 

It came about because I'm facing some trouble with alignment when interfacing with `IntelRDFPMathLib20U2` compiled with `-O3` on certain platforms.
