### ISSUE TITLE
Generated code for Protobuf failing to build

### ISSUE THREAD

**Issue by sqcsabbey** [dart-lang/ffigen#581]
I'm getting the error message:

> Error: Field 'c' requires exactly one annotation to declare its native type, which cannot be Void. dart:ffi Structs and Unions cannot have regular Dart fields.

For the ffigen'd code: 

```
/// A union for storing all possible Protobuf values. Note that owner is
/// responsible for memory management of object types.
typedef GPBGenericValue = UnnamedUnion7;

/// A union for storing all possible Protobuf values. Note that owner is
/// responsible for memory management of object types.
final class UnnamedUnion7 extends ffi.Union {
  external BOOL1 c;

  @ffi.Int()
  external int valueInt32;

  @ffi.Int()
  external int valueInt64;

  @ffi.Int()
  external int valueUInt32;

  @ffi.Int()
  external int valueUInt64;

  @ffi.Float()
  external double valueFloat;

  @ffi.Double()
  external double valueDouble;

  external ffi.Pointer<ffi.Int> valueData;

  external ffi.Pointer<ffi.Int> valueString;

  external ffi.Pointer<ffi.Int> valueMessage;

  @ffi.Int()
  external int valueEnum;
}
```

I'm not using Protobuf directly, but my Podfile.lock uses `Protobuf (3.23.0)`, and I'm trying to get this working against Dart 3.0.0 and using ffigen 8.0.2 (whatever was generated was working for me before upgrading to Dart 3 and ffigen 8). 

Any tips to help me resolve this?

Thanks!

**Comment by dcharkes** [comment]
@sqcsabbey thanks for the report.

What is the definition of `BOOL1`?

(We added bool support in https://github.com/dart-lang/ffigen/issues/315.)

**Comment by sqcsabbey** [comment]
@dcharkes, thanks for responding to my report so quickly. Here's BOOL1's definition: 

```
/// Verifies that a given value can be represented by an enum type.
typedef BOOL1 = ffi.NativeFunction<
    ffi.NativeFunction<ffi.Int Function()> Function(ffi.Pointer<ffi.Int>)>;
```

**Comment by sqcsabbey** [comment]
Here's the [header file](https://github.com/protocolbuffers/protobuf/blob/v3.23.0/objectivec/GPBRuntimeTypes.h) for it, with this typedef on line 42:

```
/**
 * Verifies that a given value can be represented by an enum type.
 * */
typedef BOOL (*GPBEnumValidationFunc)(int32_t);
```

**Comment by dcharkes** [comment]
```objectivec
/**
 * Verifies that a given value can be represented by an enum type.
 * */
typedef BOOL (*GPBEnumValidationFunc)(int32_t);
```

This is using `BOOL` and defining `GPBEnumValidationFunc`.

I'd hope the typedef would simply be this from https://developer.apple.com/documentation/objectivec/bool:

```
typedef bool BOOL;
```

Can you check you have got the right include paths and there are no errors on the FFIgen output?

**Comment by dcharkes** [comment]
Alright 👌 

Please let us know if you have further issues.
