### ISSUE TITLE
Error bug Missing Functions in the generated bindings. not all functions in the header files have bindings in the generated file by ffi gen

### ISSUE THREAD

**Issue by wajahat414** [dart-lang/ffigen#587]
###  output after running dart run ffigen --config config.yaml
<img width="1337" alt="ffigen_issue" src="https://github.com/dart-lang/ffigen/assets/73127111/bb7e1bc8-393f-4870-a131-45aaee7d947b">

### Missing Functions in the generated bindings there are many but some of them  I am listing

- ZMQ_EXPORT void *zmq_poller_new (void);
- ZMQ_EXPORT int zmq_poller_modify (void *poller, void *socket, short events);
- ZMQ_EXPORT int zmq_poller_remove (void *poller, void *socket);

**Comment by mannprerak2** [comment]
These functions are inside `#ifdef ZMQ_BUILD_DRAFT_API`, you can define a macro while parsing via compiler-opts

```bash
dart run ffigen --config config.yaml --compiler-opts="-D ZMQ_BUILD_DRAFT_API 1"
```

You can supply the `--verbose all` flag while running ffigen to print all logs, if your don't see a definition/function in it, it was skipped via libclang while parsing.
