### ISSUE TITLE
Removing wrapper.c

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#61]
We currently need `wrapper.c` because `dart:ffi` does not support passing structs by value yet (https://github.com/dart-lang/ffigen/issues/3).

However, we also have other things in `wrapper.c`, for example having some process uuid and a stack.

We should investigate whether we can remove those things and do it in Dart. Or document why it is not possible to do it in only Dart + `dart:ffi`. (That might tell us we need more features in `dart:ffi`.)

Also, we could make a branch for this package which works on the locally built https://dart-review.googlesource.com/c/sdk/+/140290, so that we can merge that brach after structs-by-value lands and is released in stable.

**Comment by dcharkes** [comment]
After some digging and discussion:

if
`clang.clang_visitChildren_wrap_root` only calls `_rootCursorVisitor` and
`clang.clang_visitChildren_wrap_structMembers` only calls `_structMembersVisitor` and
`clang.clang_visitChildren_wrap_enum` only calls `_enumCursorVisitor` and
`clang.clang_visitChildren_wrap_typedefdeclaration` only calls `_typedefdeclarationCursorVisitor` and
(etc.)
you keep a stack in Dart with what Structs you expect the next callbacks (for struct members) to be for,
you don't need a stack in C.

You still need a mapping from IsolateUUID to `_rootCursorVisitor` etc.
`dlopen` only loads the dynamic library once into memory if called multiple times.
And, `package:test` runs tests concurrently in the same VM.
When we get support for structs by value, this issue goes away, because you would pass the callback function pointer of the function in the specific isolate.

**Comment by dcharkes** [comment]
We could consider removing support for running tests concurrently (and removing the isolate uuid) by using `--concurrency=1`, if that does not make the tests run overly long (and we can somehow make it always do that without users having to specify the flag).

**Comment by mannprerak2** [comment]
Done in #164.
