### ISSUE TITLE
Unclear how to use `include-directives`

### ISSUE THREAD

**Issue by craiglabenz** [dart-lang/ffigen#617]
I have a situation where header files I use and need include other header files I don't use and don't need. I would like to have `ffigen` stop recursing at a certain point, but haven't figured out the correct mechanism.

There is one sentence of documentation around `include-directives`, which reads:

> If include-directives are not specified ffigen will generate everything directly/transitively under the entry-points.

This makes it sound like `include-directives` is the right tool for the job, but how exactly to use the option is eluding me.

**Comment by dcharkes** [comment]
<img width="705" alt="image" src="https://github.com/dart-lang/ffigen/assets/3601775/840ee619-925c-4d5a-8ed6-305dca8c95be">

It's a list of glob patterns of files to follow. The default is basically `*`. The examples show how to include all the files that have for example a certain library name in their path.

**Comment by craiglabenz** [comment]
Issue isn't *including* paths, but *excluding*.

For example, consider these 2 files:

```c
// c/data.h

include "../cc/enhanced_data.h"
struct MyStruct {}
```

and

```cc
// cc/enhanced_data.h

#include <memory>
#include <optional>
#include <string>
#include etc...

// more cc stuff
```

The C and CC code is structured such that Dart only calls things defined in `c/data.h`, but the transitive dependencies are making `ffigen` attempt to generate headers for the _entire_ surface area, including lots of stdlib libraries.

Is it possible to tell `ffigen` when to STOP following dependencies, either by `include-directives` or some other mechanism?

**Comment by mannprerak2** [comment]
@craiglabenz you can learn more about glob syntax here  - https://pub.dev/packages/glob#syntax

for your particular use case, since you only need declarations from `c/data.h` -
```yaml
headers:
  include-directives:
    - **c/data.h
```

**Comment by mannprerak2** [comment]
Closing this now, feel free to reopen or add a comment.
