### ISSUE TITLE
flutter_plugin_ffi_test.dart is failing on CI

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#619]
test_flutter/flutter_template_tests/flutter_plugin_ffi_test.dart [is failing on the latest version of flutter](https://github.com/dart-lang/ffigen/actions/runs/6154926898). You have to be on the latest flutter master channel version to see the failure.

The failure is caused by a diff between the bindings generated by ffigen, and the bindings [checked into the flutter repo](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin_ffi/lib/projectName_bindings_generated.dart.tmpl). The bindings generated by ffigen have this extra ignore line at the top.

```dart
// ignore_for_file: type=lint
```

That line started being inserted after [this commit](https://github.com/dart-lang/ffigen/pull/532), but that was months ago, and the tests only just started failing.

@dcharkes looks like we need to regenerate the bindings in the flutter plugin, or maybe add `// ignore_for_file: type=lint` to the preamble in the [plugin's config](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin_ffi/ffigen.yaml.tmpl). But I'm confused about why this has only just now started failing.

**Comment by dcharkes** [comment]
> That line started being inserted after [this commit](https://github.com/dart-lang/ffigen/pull/532), but that was months ago, and the tests only just started failing.

I bumped the pinned version of ffigen.yaml in the Flutter template 3 days ago: https://github.com/flutter/flutter/blame/master/packages/flutter_tools/templates/plugin_shared/pubspec.yaml.tmpl

And yes, I might have forgotten to regenerate the file there.

The reason we run the test here instead of on the Flutter CI is:

* https://github.com/flutter/flutter/issues/105695

**Comment by liamappelbe** [comment]
Thanks @dcharkes
