### ISSUE TITLE
ffigen generating `Pointer<Int>` instead of `Array<...>`

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/ffigen#639]
https://github.com/libexif/libexif/blob/master/libexif/exif-data.h#L47 contains the following struct:

```c
/*! Represents the entire EXIF data found in an image */
struct _ExifData
{
	/*! Data for each IFD */
	ExifContent *ifd[EXIF_IFD_COUNT];

	/*! Pointer to thumbnail image, or NULL if not available */
	unsigned char *data;

	/*! Number of bytes in thumbnail image at \c data */
	unsigned int size;

	ExifDataPrivate *priv;
};
```

When you run it through `ffigen`, it generates the following binding code:

```dart
/// ! Represents the entire EXIF data found in an image
final class _ExifData extends ffi.Struct {
  /// ! Data for each IFD
  external ffi.Pointer<ffi.Int> ifd;

  /// ! Pointer to thumbnail image, or NULL if not available
  external ffi.Pointer<ffi.UnsignedChar> data;

  /// ! Number of bytes in thumbnail image at \c data
  @ffi.UnsignedInt()
  external int size;

  external ffi.Pointer<ExifDataPrivate> priv;
}
```

I found it weird that `ExifContent *ifd[EXIF_IFD_COUNT]` translated to `external ffi.Pointer<ffi.Int> ifd`, and it made it hard to get at the element I wanted...  I tried the following:

```dart
final Pointer<ExifContent> nativeContent = foo.elementAt(ExifIfd.EXIF_IFD_GPS).cast<ExifContent>();
```

... but the program crashed whenever I tried to use that `nativeContent` pointer.

So I then tried to write a simple C library that distilled this into a case I could study more.  Here is that code:

```c
typedef struct _TestData        TestData;
typedef struct _TestContent     TestContent;
typedef struct _TestEntry       TestEntry;

typedef enum {
	IFD_0 = 0,
	IFD_1,
	IFD_EXIF,
	IFD_GPS,
	IFD_INTEROPERABILITY,
	IFD_COUNT
} Ifd;

struct _TestData
{
	TestContent *ifd[IFD_COUNT];

	unsigned int size;
};

struct _TestContent
{
        TestEntry **entries;
        unsigned int count;

	TestData *parent;
};

struct _TestEntry {
        unsigned int value;

	TestContent *parent;
};

TestData *test_data_new (void);
```

I then ran that through `ffigen`, figuring that the `TestContent *ifd[IFD_COUNT]` would again turn into `external ffi.Pointer<ffi.Int> ifd`.... but it didn't.  It instead generated the following binding code:

```dart
final class _TestData extends ffi.Struct {
  @ffi.Array.multi([5])
  external ffi.Array<ffi.Pointer<TestContent>> ifd;

  @ffi.UnsignedInt()
  external int size;
}
```

So on the one hand, this generated code makes much more sense!  But on the other hand, why didn't it do this for the `libexif` code??

**Comment by dcharkes** [comment]
Tracking refusing to generate in https://github.com/dart-lang/ffigen/issues/640.
