### ISSUE TITLE
Cannot generate bindings for simple example

### ISSUE THREAD

**Issue by kentcb** [dart-lang/ffigen#80]
Hi,

Running on Windows, followed the instructions and am getting this when attempting to generate bindings for the simple example:

```
C:\Users\Kent\Repository\ffigen\example\simple>dart pub run ffigen --verbose all
Instance of 'Stdout'
Unable to create dynamic library automatically.
If LLVM is installed, try running:
  pub run ffigen:setup -Ipath/to/llvm/include -Lpath/to/llvm/lib

C:\Users\Kent\Repository\ffigen\example\simple>clang --version
clang version 10.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

C:\Users\Kent\Repository\ffigen\example\simple>dart --version
Dart SDK version: 2.10.0-4.0.dev.flutter-0341576448 (be) (Sat Aug 8 20:25:12 2020 +0000) on "windows_x64"
```

Any pointers? (forgive the pun)

**Comment by kentcb** [comment]
Found the [relevant code](https://github.com/dart-lang/ffigen/blob/master/bin/ffigen.dart#L24). Now trying to understand what it's telling me...

**Comment by kentcb** [comment]
OK, so it's looking for `C:\Users\Kent\Repository\<<redacted>>\.dart_tool\ffigen\_v2_wrapped_clang.dll` but this is what I have in my `ffigen` directory:

![image](https://user-images.githubusercontent.com/1901832/90301032-b93c5180-dee0-11ea-9dbe-0a34af2ccdb1.png)

🤔

**Comment by kentcb** [comment]
Tried running `pub run ffigen:setup`, since that appears to be responsible for generating the `wrapped_clang.dll` (even though README only mention it in context of running tests), but I get:

```
❯ dart pub run ffigen:setup
Building Dynamic Library for libclang wrapper...
   Creating library C:\Users\Kent\Repository\<<redacted>>\.dart_tool\ffigen\_v2_wrapped_clang.lib and object C:\Users\Kent\Repository\<<redacted>>\.dart_tool\ffigen\_v2_wrapped_clang.exp
wrapper-c8b27c.o : error LNK2019: unresolved external symbol malloc referenced in function ptrToCXCursor
wrapper-c8b27c.o : error LNK2019: unresolved external symbol __acrt_iob_func referenced in function printf
wrapper-c8b27c.o : error LNK2019: unresolved external symbol free referenced in function clang_disposeString_wrap
wrapper-c8b27c.o : error LNK2019: unresolved external symbol __stdio_common_vsprintf referenced in function _vsnprintf_l
wrapper-c8b27c.o : error LNK2019: unresolved external symbol __stdio_common_vfprintf referenced in function _vfprintf_l
LINK : error LNK2001: unresolved external symbol _DllMainCRTStartup
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\lib\x86\libcmt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
C:\Users\Kent\Repository\<<redacted>>\.dart_tool\ffigen\_v2_wrapped_clang.dll : fatal error LNK1120: 6 unresolved externals

clang: error: linker command failed with exit code 1120 (use -v to see invocation)
```

**Comment by kentcb** [comment]
OK, figured it out (to the extent I need to): my Powershell profile had this in it:

```
pushd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"
cmd /c "VsDevCmd.bat&set" |
foreach {
  if ($_ -match "=") {
    $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
  }
}
popd
```

That was causing the native tooling to pick up the wrong platform/versions of stuff and preventing the `clang` build from succeeding. Once I removed that from my profile, the correct tooling was picked up and everything worked as advertised with the example project.

**Comment by mannprerak2** [comment]
Hi @kentcb 
Thank you for trying out the tool and reporting this.

I am guessing you figured it all out ☺️
You can close this issue if your error has been resolved.

Apart from tests, `pub run ffigen:setup` will only need to be called if `pub run ffigen` couldn't create the dynamic library automatically (The most common error usually is that clang isn't installed or visual studio with c++ support is missing)

I am not much of a windows user, but If you think something related to this should be addressed in the readme, feel free to make a PR.
